- name: create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - "{{ data_directory }}"
    - "{{ tests_directory }}"
    - "{{ generated_data }}"
    - "{{ success_data }}"
    - "{{ problem_data }}"

- name: copy load_testing_python_scripts
  become: true
  copy:
    src: "load_testing_python_scripts"
    dest: "{{ tests_directory }}"